//
// Created by 。 on 2023/9/15.
//

#ifndef PROJECT1_LONGESTOBSTACLECOURSEATEACHPOSITION_H
#define PROJECT1_LONGESTOBSTACLECOURSEATEACHPOSITION_H


class longestObstacleCourseAtEachPosition {

};


#endif //PROJECT1_LONGESTOBSTACLECOURSEATEACHPOSITION_H
